### ISSUE TITLE
build from source code

### ISSUE THREAD

**Issue by jdlee726** [kungsik/kimsbible#1]
for Windows 10 (incomplete)
- prerequisites
  - mysql server, create tables
  - install python3, pycharm
  - add enviromment variable, e.g., `PYTHONPATH=D:\work\proj_python` 
- `cd %PYTHONPATH%`
- `git clone https://github.com/kungsik/kimsbible.git`
- `cd kimsbible`
- `git clone https://github.com/kungsik/text-fabric-data.git`
- pip install ( in project virtualenv )
```
pip install flask-login flask_mail flask_dance
pip install text-fabric
pip install pymysql bs4 whoosh
```
- create and edit lib/config.py from lib/config.sample.py, and add the following properties
```
mail_server = ""
mail_username = ""
mail_password = ""
```
- edit oauth.py
```
app.config["FACEBOOK_OAUTH_CLIENT_ID"] = 
app.config["FACEBOOK_OAUTH_CLIENT_SECRET"] = 
os.environ['OAUTHLIB_INSECURE_TRANSPORT'] = 
```
- start flask server

**Comment by kungsik** [comment]
Many thanks for the kind instruction. :) I have to manage the readme file. And you should also install the text-fabric source from https://github.com/kungsik/text-fabric-data 
This folder is to be located in ~/home folder in Linux. I'm not sure in case of windows. But the debugger of the text-fabric will indicate the location of that folder.

**Comment by jdlee726** [comment]
as your instructions, I updated previous note.
But, when I try to start flask, I'v got the following errors.
`   |     0.00s Feature "phono" not available in`

The full loggings are as the following.
```
FLASK_APP = app.py
FLASK_ENV = development
FLASK_DEBUG = 0
In folder D:/work/proj_other/kimsbible
D:\work\proj_other\kimsbible\venv\Scripts\python.exe "C:\Program Files\JetBrains\PyCharm 2019.2.3\helpers\pydev\pydevd.py" --module --multiproc --qt-support=auto --client 127.0.0.1 --port 53180 --file flask run
pydev debugger: process 1472 is connecting

Connected to pydev debugger (build 192.6817.19)
 * Serving Flask app "app.py"
 * Environment: development
 * Debug mode: off
This is Text-Fabric 7.8.12
Api reference : https://annotation.github.io/text-fabric/Api/Fabric/

108 features found and 0 ignored
  0.00s loading features ...
   |     0.00s No structure info in otext, the structure part of the T-API cannot be used
   |     0.00s M otext                from text-fabric-data/hebrew/etcbc4c
   |     0.00s Feature "phono" not available in
   |     0.08s B otype                from text-fabric-data/hebrew/etcbc4c
   |   text-fabric-data/hebrew/etcbc4c
  7.51s Not all features could be loaded/computed
   |     1.12s B oslots               from text-fabric-data/hebrew/etcbc4c
   |     0.00s M otext                from text-fabric-data/hebrew/etcbc4c
   |     0.10s B g_lex_utf8           from text-fabric-data/hebrew/etcbc4c
   |     0.00s B book@el              from text-fabric-data/hebrew/etcbc4c
   |     0.00s B book@pa              from text-fabric-data/hebrew/etcbc4c
   |     0.00s B book@de              from text-fabric-data/hebrew/etcbc4c
   |     0.09s B lex0                 from text-fabric-data/hebrew/etcbc4c
   |     0.10s B lex_utf8             from text-fabric-data/hebrew/etcbc4c
   |     0.09s B trailer              from text-fabric-data/hebrew/etcbc4c
   |     0.07s B trailer_utf8         from text-fabric-data/hebrew/etcbc4c
   |     0.00s B book@ko              from text-fabric-data/hebrew/etcbc4c
   |     0.00s B book@zh              from text-fabric-data/hebrew/etcbc4c
   |     0.00s B book@da              from text-fabric-data/hebrew/etcbc4c
   |     0.00s B book@ja              from text-fabric-data/hebrew/etcbc4c
   |     0.00s B qere_utf8            from text-fabric-data/hebrew/etcbc4c
   |     0.00s B book@syc             from text-fabric-data/hebrew/etcbc4c
   |     0.00s B book@ar              from text-fabric-data/hebrew/etcbc4c
   |     0.00s B book@fa              from text-fabric-data/hebrew/etcbc4c
   |     0.00s B book@pt              from text-fabric-data/hebrew/etcbc4c
   |     0.17s B g_word_utf8          from text-fabric-data/hebrew/etcbc4c
   |     0.00s B qere                 from text-fabric-data/hebrew/etcbc4c
   |     0.00s B qere_trailer_utf8    from text-fabric-data/hebrew/etcbc4c
   |     0.00s B qere_trailer         from text-fabric-data/hebrew/etcbc4c
   |     0.00s B book@hi              from text-fabric-data/hebrew/etcbc4c
   |     0.16s B g_word               from text-fabric-data/hebrew/etcbc4c
   |     0.00s B book@sw              from text-fabric-data/hebrew/etcbc4c
   |     0.00s B book@bn              from text-fabric-data/hebrew/etcbc4c
   |     0.12s B g_lex                from text-fabric-data/hebrew/etcbc4c
   |     0.01s B book                 from text-fabric-data/hebrew/etcbc4c
   |     0.00s B book@es              from text-fabric-data/hebrew/etcbc4c
   |     0.00s B book@fr              from text-fabric-data/hebrew/etcbc4c
   |     0.00s B book@id              from text-fabric-data/hebrew/etcbc4c
   |     0.00s B book@ru              from text-fabric-data/hebrew/etcbc4c
   |     0.00s B book@tr              from text-fabric-data/hebrew/etcbc4c
   |     0.00s B book@nl              from text-fabric-data/hebrew/etcbc4c
   |     0.00s B book@ur              from text-fabric-data/hebrew/etcbc4c
   |     0.11s B g_cons_utf8          from text-fabric-data/hebrew/etcbc4c
   |     0.11s B g_cons               from text-fabric-data/hebrew/etcbc4c
   |     0.00s B book@en              from text-fabric-data/hebrew/etcbc4c
   |     0.00s B verse                from text-fabric-data/hebrew/etcbc4c
   |     0.00s B book@he              from text-fabric-data/hebrew/etcbc4c
   |     0.00s B chapter              from text-fabric-data/hebrew/etcbc4c
   |     0.00s B book@am              from text-fabric-data/hebrew/etcbc4c
   |     0.00s B book@yo              from text-fabric-data/hebrew/etcbc4c
   |     0.00s B book@la              from text-fabric-data/hebrew/etcbc4c
   |     0.00s B __levels__           from otype, oslots, otext
   |     0.05s B __order__            from otype, oslots, __levels__
   |     0.05s B __rank__             from otype, __order__
   |     1.69s B __levUp__            from otype, oslots, __rank__
   |     1.26s B __levDown__          from otype, __levUp__, __rank__
   |     0.74s B __boundary__         from otype, oslots, __rank__
   |     0.01s B __sections__         from otype, oslots, otext, __levUp__, __levels__, book, chapter, verse
   |     0.00s = book                 from text-fabric-data/hebrew/etcbc4c
   |     0.00s = chapter              from text-fabric-data/hebrew/etcbc4c
   |     0.00s = verse                from text-fabric-data/hebrew/etcbc4c
   |     0.07s B nu                   from text-fabric-data/hebrew/etcbc4c
   |     0.08s B gn                   from text-fabric-data/hebrew/etcbc4c
   |     0.08s B ps                   from text-fabric-data/hebrew/etcbc4c
   |     0.08s B vt                   from text-fabric-data/hebrew/etcbc4c
   |     0.08s B vs                   from text-fabric-data/hebrew/etcbc4c
   |     0.09s B st                   from text-fabric-data/hebrew/etcbc4c
   |     0.00s = otype                from text-fabric-data/hebrew/etcbc4c
   |     0.16s B typ                  from text-fabric-data/hebrew/etcbc4c
   |     0.04s B function             from text-fabric-data/hebrew/etcbc4c
   |     0.09s B det                  from text-fabric-data/hebrew/etcbc4c
   |     0.08s B pdp                  from text-fabric-data/hebrew/etcbc4c
   |     0.00s = qere_utf8            from text-fabric-data/hebrew/etcbc4c
   |     0.00s = qere_trailer_utf8    from text-fabric-data/hebrew/etcbc4c
   |     0.00s = g_word_utf8          from text-fabric-data/hebrew/etcbc4c
   |     0.00s = trailer_utf8         from text-fabric-data/hebrew/etcbc4c
   |     0.00s = lex_utf8             from text-fabric-data/hebrew/etcbc4c
   |     0.10s B lex                  from text-fabric-data/hebrew/etcbc4c
   |     0.01s B voc_utf8             from text-fabric-data/hebrew/etcbc4c
   |     0.08s B g_prs_utf8           from text-fabric-data/hebrew/etcbc4c
   |     0.08s B g_uvf_utf8           from text-fabric-data/hebrew/etcbc4c
   |     0.08s B prs_gn               from text-fabric-data/hebrew/etcbc4c
   |     0.08s B prs_nu               from text-fabric-data/hebrew/etcbc4c
   |     0.08s B prs_ps               from text-fabric-data/hebrew/etcbc4c
   |     0.00s = g_cons_utf8          from text-fabric-data/hebrew/etcbc4c
   |     0.00s B gloss                from text-fabric-data/hebrew/etcbc4c
Traceback (most recent call last):
  File "D:\work\proj_other\kimsbible\venv\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "D:\work\proj_other\kimsbible\venv\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\work\proj_other\kimsbible\venv\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\work\proj_other\kimsbible\venv\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "D:\work\proj_other\kimsbible\venv\lib\site-packages\click\decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "D:\work\proj_other\kimsbible\venv\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "D:\work\proj_other\kimsbible\venv\lib\site-packages\flask\cli.py", line 848, in run_command
    app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
  File "D:\work\proj_other\kimsbible\venv\lib\site-packages\flask\cli.py", line 305, in __init__
    self._load_unlocked()
  File "D:\work\proj_other\kimsbible\venv\lib\site-packages\flask\cli.py", line 330, in _load_unlocked
    self._app = rv = self.loader()
  File "D:\work\proj_other\kimsbible\venv\lib\site-packages\flask\cli.py", line 388, in load_app
    app = locate_app(self, import_name, name)
  File "D:\work\proj_other\kimsbible\venv\lib\site-packages\flask\cli.py", line 240, in locate_app
    __import__(module_name)
  File "D:\work\proj_other\kimsbible\__init__.py", line 12, in <module>
    import kimsbible.bhsheb
  File "D:\work\proj_other\kimsbible\bhsheb.py", line 39, in <module>
    api.makeAvailableIn(globals())
AttributeError: 'bool' object has no attribute 'makeAvailableIn'

Process finished with exit code 1
```

**Comment by kungsik** [comment]
Thanks for your report. There are several problems here.
I supplemented and committed the phono file. Please pull the codes again (text-fabric-data).
There are additional python libraries to be installed, and you have to set the sql db tables. 
I just realized I should prepare the well organized documentation for development.
So sorry for this uncomfortable situation, and I will show the dev guide shortly.

**Comment by jdlee726** [comment]
@kungsik , with your help, I finally start flask server without errors.
```
FLASK_APP = __init__.py
FLASK_ENV = development
FLASK_DEBUG = 0
In folder D:/work/proj_other/kimsbible
D:\work\proj_other\kimsbible\venv\Scripts\python.exe -m flask run
 * Serving Flask app "__init__.py"
 * Environment: development
 * Debug mode: off
This is Text-Fabric 7.8.12
Api reference : https://annotation.github.io/text-fabric/Api/Fabric/

111 features found and 0 ignored
  0.00s loading features ...
   |     0.00s No structure info in otext, the structure part of the T-API cannot be used
  7.43s All features loaded/computed - for details use loadLog()
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
```

But, when I tried to access `http://127.0.0.1:5000/`, I'v got the following errors.
```
pymysql.err.ProgrammingError: (1146, "Table 'kimsbible.commentary' doesn't exist")
127.0.0.1 - - [07/Oct/2019 11:44:47] "GET / HTTP/1.1" 500 -
```
I'm looking for some db scripts.
